#
# Copyright (C) 2020 Tuono, Inc.
# All Rights Reserved
#
---
name: tuono-vault-jwt-plugin-release
on:
  release:
    types:
      - published

jobs:
  jwt-plugin-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - uses: actions/checkout@v2

      - name: Build and publish plugin to Gemfury
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          make jwt-plugin

      - name: Publish plugin
        id: tuono-vault-jwt-plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.assets_url }}
          asset_path: jwt-plugin/bin/tuono-jwt-plugin.tar.gz
          asset_name: tuono-jwt-plugin.tar.gz
          asset_content_type: application/zip
